version: '3.8'

services:
  legal-assistant:
    build: .
    container_name: nepal_legal_assistant
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./chroma_db:/app/chroma_db
    restart: unless-stopped